### ISSUE TITLE
How to change the width of AlertDialog

### ISSUE THREAD

**Issue by Ofer-Gal** [SPFxAppDev/fluentui-react-controls#6]
My code:
```
                    const jsx: JSX.Element = <>{dataItems}</>;
                    const args: AlertDialogPluginProps = {
                        title: `Job ${jobNumber} Has Open Files`,
                        content: jsx,
                        buttonText: 'Continue, Closed Files',
                        className: 'myalertdialog',                        
                    };
                    await Plugins.AlertDialog.open(args);
```
My CSS
```
.myalertdialog {
  max-width: unset;
  width: 100%;
  border: 1px solid red;
}
```

That does not change the width of the popup. it is always 340 px (because of:
```
@media (min-width: 480px) {
    .main-236 {
        width: auto;
        max-width: 340px;
        min-width: 288px;
    }
}
```

How can I change the width of the pop up?

Thanks

**Comment by SPFxAppDev** [comment]
Hi, you could override the css like this:

```css
.myalertdialog .ms-Dialog-main {
  max-width: unset;
  min-width: 100%;
  border: 1px solid red;
}
```
Result:
![image](https://github.com/user-attachments/assets/2800d8f1-818a-49d9-944d-ea9b45f21df8)

PS: If you use the controls in a spfx project with scss modules, don't forget to wrap the css rules via `:global` 

```scss
.myalertdialog {
:global {
 .ms-Dialog-main {
  max-width: unset;
  min-width: 100%;
  border: 1px solid red;
  }
}
}
```
